### ISSUE TITLE
pyopf.io.load doesn't handle absolute windows paths

### ISSUE THREAD

**Issue by Wumpf** [Pix4D/pyopf#6]
Passing in an absolute path on windows results in this exception:
```
Traceback (most recent call last):
  File "C:\dev\rerun\rerun\examples\python\open_photogrammetry_format\main.py", line 220, in <module>
    main()
  File "C:\dev\rerun\rerun\examples\python\open_photogrammetry_format\main.py", line 209, in main
    project = OPFProject.from_dataset(args.dataset, log_as_frames=not args.no_frames)
  File "C:\dev\rerun\rerun\examples\python\open_photogrammetry_format\main.py", line 107, in from_dataset
    return cls(DATASET_DIR / spec.dir_name / "project.opf", log_as_frames=log_as_frames)
  File "C:\dev\rerun\rerun\examples\python\open_photogrammetry_format\main.py", line 85, in __init__
    self.project = resolve(load(str(path)))
  File "C:\Python310\lib\site-packages\pyopf\io\loaders.py", line 143, in load
    accepted, params = test(resource, base_uri, additional_resources)
  File "C:\Python310\lib\site-packages\pyopf\io\loaders.py", line 73, in _test_json_resource
    uri = join_uris(resource, base_uri)
  File "C:\Python310\lib\site-packages\pyopf\io\loaders.py", line 31, in join_uris
    raise RuntimeError("Non-file URIs are not supported")
RuntimeError: Non-file URIs are not supported
```

After a bit try and error I figured out that this can be worked around with DOS UNC paths
```py
"\\\\.\\" + str(path.absolute()) if os.name == "nt" else str(path)
```
See also https://github.com/rerun-io/rerun/pull/3705

**Comment by krahenbuhl** [comment]
Hi @Wumpf, this should be fixed in the new version we just released (1.2.0). Please feel free to reopen if you still have issues! Thanks
